language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
# command to install dependencies
install:
    - pip install -r test-requirements.txt --use-mirrors
    - pip install .
# command to run tests
script:
    - python testproject/manage.py test --settings=testproject.settings parting
notifications:
  email:
    - dan@fezconsulting.com

